package com.neobyte.footbalschedule.models

import com.google.gson.annotations.SerializedName

data class Player(
    @SerializedName("idPlayer") val idPlayer: String? = "",
    @SerializedName("idTeam") val idTeam: String? = "",
    @SerializedName("idSoccerXML") val idSoccerXML: String? = "",
    @SerializedName("idPlayerManager") val idPlayerManager: Any? = Any(),
    @SerializedName("strNationality") val strNationality: String? = "",
    @SerializedName("strPlayer") val strPlayer: String? = "",
    @SerializedName("strTeam") val strTeam: String? = "",
    @SerializedName("strSport") val strSport: String? = "",
    @SerializedName("intSoccerXMLTeamID") val intSoccerXMLTeamID: Any? = Any(),
    @SerializedName("dateBorn") val dateBorn: String? = "",
    @SerializedName("dateSigned") val dateSigned: Any? = Any(),
    @SerializedName("strSigning") val strSigning: String? = "",
    @SerializedName("strWage") val strWage: String? = "",
    @SerializedName("strBirthLocation") val strBirthLocation: String? = "",
    @SerializedName("strDescriptionEN") val strDescriptionEN: String? = "",
    @SerializedName("strDescriptionDE") val strDescriptionDE: Any? = Any(),
    @SerializedName("strDescriptionFR") val strDescriptionFR: Any? = Any(),
    @SerializedName("strDescriptionCN") val strDescriptionCN: Any? = Any(),
    @SerializedName("strDescriptionIT") val strDescriptionIT: Any? = Any(),
    @SerializedName("strDescriptionJP") val strDescriptionJP: Any? = Any(),
    @SerializedName("strDescriptionRU") val strDescriptionRU: Any? = Any(),
    @SerializedName("strDescriptionES") val strDescriptionES: Any? = Any(),
    @SerializedName("strDescriptionPT") val strDescriptionPT: Any? = Any(),
    @SerializedName("strDescriptionSE") val strDescriptionSE: Any? = Any(),
    @SerializedName("strDescriptionNL") val strDescriptionNL: Any? = Any(),
    @SerializedName("strDescriptionHU") val strDescriptionHU: Any? = Any(),
    @SerializedName("strDescriptionNO") val strDescriptionNO: Any? = Any(),
    @SerializedName("strDescriptionIL") val strDescriptionIL: Any? = Any(),
    @SerializedName("strDescriptionPL") val strDescriptionPL: Any? = Any(),
    @SerializedName("strGender") val strGender: String? = "",
    @SerializedName("strPosition") val strPosition: String? = "",
    @SerializedName("strCollege") val strCollege: Any? = Any(),
    @SerializedName("strFacebook") val strFacebook: String? = "",
    @SerializedName("strWebsite") val strWebsite: String? = "",
    @SerializedName("strTwitter") val strTwitter: String? = "",
    @SerializedName("strInstagram") val strInstagram: String? = "",
    @SerializedName("strYoutube") val strYoutube: String? = "",
    @SerializedName("strHeight") val strHeight: String? = "",
    @SerializedName("strWeight") val strWeight: String? = "",
    @SerializedName("intLoved") val intLoved: String? = "",
    @SerializedName("strThumb") val strThumb: String? = "",
    @SerializedName("strCutout") val strCutout: Any? = Any(),
    @SerializedName("strBanner") val strBanner: Any? = Any(),
    @SerializedName("strFanart1") val strFanart1: Any? = Any(),
    @SerializedName("strFanart2") val strFanart2: Any? = Any(),
    @SerializedName("strFanart3") val strFanart3: Any? = Any(),
    @SerializedName("strFanart4") val strFanart4: Any? = Any(),
    @SerializedName("strLocked") val strLocked: String? = ""
)